apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pgadmin.fullname" . }}-pgadmin
  namespace: {{ .Values.pgadmin_app_namespace }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pgadmin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: meshdb-pgadmin-app
        {{- include "pgadmin.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.pgadmin.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-pgadmin
          securityContext:
            {{- toYaml .Values.pgadmin.securityContext | nindent 12 }}
          image: "{{ .Values.pgadmin.image.repository }}:{{ .Values.pgadmin.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.pgadmin.port }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: pgadmin-secrets
          env:
            - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
              value: "False"
            - name: PGADMIN_CONFIG_MAIL_USE_TLS
              value: "True"
          {{ if eq .Values.pgadmin.liveness_probe "true" }}
          livenessProbe:
           exec:
             command:
               - curl
               - http://127.0.0.1:{{ .Values.pgadmin.port }}
           periodSeconds: 3
           initialDelaySeconds: 4
           timeoutSeconds: 3
           {{ end }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.pgadmin.resources | nindent 12 }}
      {{- with .Values.pgadmin.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pgadmin.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pgadmin.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
