name: Docker build only

on: [pull_request]

permissions: read-all

jobs:
  docker_build_only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@601a80b39c9405e50806ae38af30926f9d957c47
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: "test:latest"
