name: Lint

on: [pull_request]

permissions: read-all

jobs:
  invoke_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v4
        with:
          python-version: '3.11'
      - name: "Upgrade pip"
        run: "pip install --upgrade pip"
      - name: "Print python version"
        run: "python --version"
      - name: "Install package"
        run: pip install ".[dev]"
      - name: "Run lint checks"
        run: invoke lint
    env:
      DJANGO_SECRET_KEY: SECRET_KEY
